"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Review = void 0;
var typeorm_1 = require("typeorm");
var class_transformer_1 = require("class-transformer");
var business_entity_1 = require("./business.entity");
var user_entity_1 = require("./user.entity");
var review_helpful_vote_entity_1 = require("./review-helpful-vote.entity");
var Review = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('reviews')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _businessId_decorators;
    var _businessId_initializers = [];
    var _businessId_extraInitializers = [];
    var _userId_decorators;
    var _userId_initializers = [];
    var _userId_extraInitializers = [];
    var _rating_decorators;
    var _rating_initializers = [];
    var _rating_extraInitializers = [];
    var _title_decorators;
    var _title_initializers = [];
    var _title_extraInitializers = [];
    var _comment_decorators;
    var _comment_initializers = [];
    var _comment_extraInitializers = [];
    var _images_decorators;
    var _images_initializers = [];
    var _images_extraInitializers = [];
    var _helpfulCount_decorators;
    var _helpfulCount_initializers = [];
    var _helpfulCount_extraInitializers = [];
    var _isVerifiedPurchase_decorators;
    var _isVerifiedPurchase_initializers = [];
    var _isVerifiedPurchase_extraInitializers = [];
    var _isApproved_decorators;
    var _isApproved_initializers = [];
    var _isApproved_extraInitializers = [];
    var _isSuspicious_decorators;
    var _isSuspicious_initializers = [];
    var _isSuspicious_extraInitializers = [];
    var _suspicionScore_decorators;
    var _suspicionScore_initializers = [];
    var _suspicionScore_extraInitializers = [];
    var _suspicionReason_decorators;
    var _suspicionReason_initializers = [];
    var _suspicionReason_extraInitializers = [];
    var _ipAddress_decorators;
    var _ipAddress_initializers = [];
    var _ipAddress_extraInitializers = [];
    var _vendorResponse_decorators;
    var _vendorResponse_initializers = [];
    var _vendorResponse_extraInitializers = [];
    var _vendorResponseAt_decorators;
    var _vendorResponseAt_initializers = [];
    var _vendorResponseAt_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _business_decorators;
    var _business_initializers = [];
    var _business_extraInitializers = [];
    var _user_decorators;
    var _user_initializers = [];
    var _user_extraInitializers = [];
    var _helpfulVotes_decorators;
    var _helpfulVotes_initializers = [];
    var _helpfulVotes_extraInitializers = [];
    var Review = _classThis = /** @class */ (function () {
        function Review_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.businessId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _businessId_initializers, void 0));
            this.userId = (__runInitializers(this, _businessId_extraInitializers), __runInitializers(this, _userId_initializers, void 0));
            this.rating = (__runInitializers(this, _userId_extraInitializers), __runInitializers(this, _rating_initializers, void 0));
            this.title = (__runInitializers(this, _rating_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.comment = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _comment_initializers, void 0));
            this.images = (__runInitializers(this, _comment_extraInitializers), __runInitializers(this, _images_initializers, void 0));
            this.helpfulCount = (__runInitializers(this, _images_extraInitializers), __runInitializers(this, _helpfulCount_initializers, void 0));
            this.isVerifiedPurchase = (__runInitializers(this, _helpfulCount_extraInitializers), __runInitializers(this, _isVerifiedPurchase_initializers, void 0));
            this.isApproved = (__runInitializers(this, _isVerifiedPurchase_extraInitializers), __runInitializers(this, _isApproved_initializers, void 0));
            this.isSuspicious = (__runInitializers(this, _isApproved_extraInitializers), __runInitializers(this, _isSuspicious_initializers, void 0));
            this.suspicionScore = (__runInitializers(this, _isSuspicious_extraInitializers), __runInitializers(this, _suspicionScore_initializers, void 0));
            this.suspicionReason = (__runInitializers(this, _suspicionScore_extraInitializers), __runInitializers(this, _suspicionReason_initializers, void 0));
            this.ipAddress = (__runInitializers(this, _suspicionReason_extraInitializers), __runInitializers(this, _ipAddress_initializers, void 0));
            this.vendorResponse = (__runInitializers(this, _ipAddress_extraInitializers), __runInitializers(this, _vendorResponse_initializers, void 0));
            this.vendorResponseAt = (__runInitializers(this, _vendorResponse_extraInitializers), __runInitializers(this, _vendorResponseAt_initializers, void 0));
            this.createdAt = (__runInitializers(this, _vendorResponseAt_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            // Relations
            this.business = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _business_initializers, void 0));
            this.user = (__runInitializers(this, _business_extraInitializers), __runInitializers(this, _user_initializers, void 0));
            this.helpfulVotes = (__runInitializers(this, _user_extraInitializers), __runInitializers(this, _helpfulVotes_initializers, void 0));
            __runInitializers(this, _helpfulVotes_extraInitializers);
        }
        return Review_1;
    }());
    __setFunctionName(_classThis, "Review");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _businessId_decorators = [(0, typeorm_1.Column)({ name: 'business_id', type: 'uuid' }), (0, typeorm_1.Index)()];
        _userId_decorators = [(0, typeorm_1.Column)({ name: 'user_id', type: 'uuid' }), (0, typeorm_1.Index)()];
        _rating_decorators = [(0, typeorm_1.Column)({ type: 'int' }), (0, typeorm_1.Index)()];
        _title_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _comment_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _images_decorators = [(0, typeorm_1.Column)({ type: 'jsonb', default: '[]' })];
        _helpfulCount_decorators = [(0, typeorm_1.Column)({ name: 'helpful_count', default: 0 })];
        _isVerifiedPurchase_decorators = [(0, typeorm_1.Column)({ name: 'is_verified_purchase', default: false })];
        _isApproved_decorators = [(0, typeorm_1.Column)({ name: 'is_approved', default: true }), (0, typeorm_1.Index)()];
        _isSuspicious_decorators = [(0, typeorm_1.Column)({ name: 'is_suspicious', default: false }), (0, typeorm_1.Index)()];
        _suspicionScore_decorators = [(0, typeorm_1.Column)({ name: 'suspicion_score', type: 'float', default: 0 })];
        _suspicionReason_decorators = [(0, typeorm_1.Column)({ name: 'suspicion_reason', nullable: true, type: 'text' })];
        _ipAddress_decorators = [(0, typeorm_1.Column)({ name: 'ip_address', nullable: true }), (0, typeorm_1.Index)()];
        _vendorResponse_decorators = [(0, typeorm_1.Column)({ name: 'vendor_response', nullable: true, type: 'text' })];
        _vendorResponseAt_decorators = [(0, typeorm_1.Column)({ name: 'vendor_response_at', nullable: true, type: 'timestamp' })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ name: 'created_at' }), (0, typeorm_1.Index)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ name: 'updated_at' })];
        _business_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.ManyToOne)(function () { return business_entity_1.Listing; }, function (listing) { return listing.reviews; }), (0, typeorm_1.JoinColumn)({ name: 'business_id' })];
        _user_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.ManyToOne)(function () { return user_entity_1.User; }, function (user) { return user.reviews; }), (0, typeorm_1.JoinColumn)({ name: 'user_id' })];
        _helpfulVotes_decorators = [(0, typeorm_1.OneToMany)(function () { return review_helpful_vote_entity_1.ReviewHelpfulVote; }, function (vote) { return vote.review; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _businessId_decorators, { kind: "field", name: "businessId", static: false, private: false, access: { has: function (obj) { return "businessId" in obj; }, get: function (obj) { return obj.businessId; }, set: function (obj, value) { obj.businessId = value; } }, metadata: _metadata }, _businessId_initializers, _businessId_extraInitializers);
        __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: function (obj) { return "userId" in obj; }, get: function (obj) { return obj.userId; }, set: function (obj, value) { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _userId_extraInitializers);
        __esDecorate(null, null, _rating_decorators, { kind: "field", name: "rating", static: false, private: false, access: { has: function (obj) { return "rating" in obj; }, get: function (obj) { return obj.rating; }, set: function (obj, value) { obj.rating = value; } }, metadata: _metadata }, _rating_initializers, _rating_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: function (obj) { return "title" in obj; }, get: function (obj) { return obj.title; }, set: function (obj, value) { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _comment_decorators, { kind: "field", name: "comment", static: false, private: false, access: { has: function (obj) { return "comment" in obj; }, get: function (obj) { return obj.comment; }, set: function (obj, value) { obj.comment = value; } }, metadata: _metadata }, _comment_initializers, _comment_extraInitializers);
        __esDecorate(null, null, _images_decorators, { kind: "field", name: "images", static: false, private: false, access: { has: function (obj) { return "images" in obj; }, get: function (obj) { return obj.images; }, set: function (obj, value) { obj.images = value; } }, metadata: _metadata }, _images_initializers, _images_extraInitializers);
        __esDecorate(null, null, _helpfulCount_decorators, { kind: "field", name: "helpfulCount", static: false, private: false, access: { has: function (obj) { return "helpfulCount" in obj; }, get: function (obj) { return obj.helpfulCount; }, set: function (obj, value) { obj.helpfulCount = value; } }, metadata: _metadata }, _helpfulCount_initializers, _helpfulCount_extraInitializers);
        __esDecorate(null, null, _isVerifiedPurchase_decorators, { kind: "field", name: "isVerifiedPurchase", static: false, private: false, access: { has: function (obj) { return "isVerifiedPurchase" in obj; }, get: function (obj) { return obj.isVerifiedPurchase; }, set: function (obj, value) { obj.isVerifiedPurchase = value; } }, metadata: _metadata }, _isVerifiedPurchase_initializers, _isVerifiedPurchase_extraInitializers);
        __esDecorate(null, null, _isApproved_decorators, { kind: "field", name: "isApproved", static: false, private: false, access: { has: function (obj) { return "isApproved" in obj; }, get: function (obj) { return obj.isApproved; }, set: function (obj, value) { obj.isApproved = value; } }, metadata: _metadata }, _isApproved_initializers, _isApproved_extraInitializers);
        __esDecorate(null, null, _isSuspicious_decorators, { kind: "field", name: "isSuspicious", static: false, private: false, access: { has: function (obj) { return "isSuspicious" in obj; }, get: function (obj) { return obj.isSuspicious; }, set: function (obj, value) { obj.isSuspicious = value; } }, metadata: _metadata }, _isSuspicious_initializers, _isSuspicious_extraInitializers);
        __esDecorate(null, null, _suspicionScore_decorators, { kind: "field", name: "suspicionScore", static: false, private: false, access: { has: function (obj) { return "suspicionScore" in obj; }, get: function (obj) { return obj.suspicionScore; }, set: function (obj, value) { obj.suspicionScore = value; } }, metadata: _metadata }, _suspicionScore_initializers, _suspicionScore_extraInitializers);
        __esDecorate(null, null, _suspicionReason_decorators, { kind: "field", name: "suspicionReason", static: false, private: false, access: { has: function (obj) { return "suspicionReason" in obj; }, get: function (obj) { return obj.suspicionReason; }, set: function (obj, value) { obj.suspicionReason = value; } }, metadata: _metadata }, _suspicionReason_initializers, _suspicionReason_extraInitializers);
        __esDecorate(null, null, _ipAddress_decorators, { kind: "field", name: "ipAddress", static: false, private: false, access: { has: function (obj) { return "ipAddress" in obj; }, get: function (obj) { return obj.ipAddress; }, set: function (obj, value) { obj.ipAddress = value; } }, metadata: _metadata }, _ipAddress_initializers, _ipAddress_extraInitializers);
        __esDecorate(null, null, _vendorResponse_decorators, { kind: "field", name: "vendorResponse", static: false, private: false, access: { has: function (obj) { return "vendorResponse" in obj; }, get: function (obj) { return obj.vendorResponse; }, set: function (obj, value) { obj.vendorResponse = value; } }, metadata: _metadata }, _vendorResponse_initializers, _vendorResponse_extraInitializers);
        __esDecorate(null, null, _vendorResponseAt_decorators, { kind: "field", name: "vendorResponseAt", static: false, private: false, access: { has: function (obj) { return "vendorResponseAt" in obj; }, get: function (obj) { return obj.vendorResponseAt; }, set: function (obj, value) { obj.vendorResponseAt = value; } }, metadata: _metadata }, _vendorResponseAt_initializers, _vendorResponseAt_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _business_decorators, { kind: "field", name: "business", static: false, private: false, access: { has: function (obj) { return "business" in obj; }, get: function (obj) { return obj.business; }, set: function (obj, value) { obj.business = value; } }, metadata: _metadata }, _business_initializers, _business_extraInitializers);
        __esDecorate(null, null, _user_decorators, { kind: "field", name: "user", static: false, private: false, access: { has: function (obj) { return "user" in obj; }, get: function (obj) { return obj.user; }, set: function (obj, value) { obj.user = value; } }, metadata: _metadata }, _user_initializers, _user_extraInitializers);
        __esDecorate(null, null, _helpfulVotes_decorators, { kind: "field", name: "helpfulVotes", static: false, private: false, access: { has: function (obj) { return "helpfulVotes" in obj; }, get: function (obj) { return obj.helpfulVotes; }, set: function (obj, value) { obj.helpfulVotes = value; } }, metadata: _metadata }, _helpfulVotes_initializers, _helpfulVotes_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Review = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Review = _classThis;
}();
exports.Review = Review;
