"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = exports.UserRole = void 0;
var typeorm_1 = require("typeorm");
var class_transformer_1 = require("class-transformer");
var vendor_entity_1 = require("./vendor.entity");
var review_entity_1 = require("./review.entity");
var lead_entity_1 = require("./lead.entity");
var favorite_entity_1 = require("./favorite.entity");
var notification_entity_1 = require("./notification.entity");
var comment_entity_1 = require("./comment.entity");
var follow_entity_1 = require("./follow.entity");
var affiliate_entity_1 = require("./affiliate.entity");
var UserRole;
(function (UserRole) {
    UserRole["USER"] = "user";
    UserRole["VENDOR"] = "vendor";
    UserRole["ADMIN"] = "admin";
    UserRole["SUPERADMIN"] = "superadmin";
})(UserRole || (exports.UserRole = UserRole = {}));
var User = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('users')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _password_decorators;
    var _password_initializers = [];
    var _password_extraInitializers = [];
    var _email_decorators;
    var _email_initializers = [];
    var _email_extraInitializers = [];
    var _phone_decorators;
    var _phone_initializers = [];
    var _phone_extraInitializers = [];
    var _fullName_decorators;
    var _fullName_initializers = [];
    var _fullName_extraInitializers = [];
    var _avatarUrl_decorators;
    var _avatarUrl_initializers = [];
    var _avatarUrl_extraInitializers = [];
    var _role_decorators;
    var _role_initializers = [];
    var _role_extraInitializers = [];
    var _isActive_decorators;
    var _isActive_initializers = [];
    var _isActive_extraInitializers = [];
    var _isEmailVerified_decorators;
    var _isEmailVerified_initializers = [];
    var _isEmailVerified_extraInitializers = [];
    var _isPhoneVerified_decorators;
    var _isPhoneVerified_initializers = [];
    var _isPhoneVerified_extraInitializers = [];
    var _isOnline_decorators;
    var _isOnline_initializers = [];
    var _isOnline_extraInitializers = [];
    var _city_decorators;
    var _city_initializers = [];
    var _city_extraInitializers = [];
    var _state_decorators;
    var _state_initializers = [];
    var _state_extraInitializers = [];
    var _country_decorators;
    var _country_initializers = [];
    var _country_extraInitializers = [];
    var _googleId_decorators;
    var _googleId_initializers = [];
    var _googleId_extraInitializers = [];
    var _provider_decorators;
    var _provider_initializers = [];
    var _provider_extraInitializers = [];
    var _deviceToken_decorators;
    var _deviceToken_initializers = [];
    var _deviceToken_extraInitializers = [];
    var _pushSubscriptions_decorators;
    var _pushSubscriptions_initializers = [];
    var _pushSubscriptions_extraInitializers = [];
    var _lastLoginAt_decorators;
    var _lastLoginAt_initializers = [];
    var _lastLoginAt_extraInitializers = [];
    var _lastLogoutAt_decorators;
    var _lastLogoutAt_initializers = [];
    var _lastLogoutAt_extraInitializers = [];
    var _lastActiveAt_decorators;
    var _lastActiveAt_initializers = [];
    var _lastActiveAt_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _vendor_decorators;
    var _vendor_initializers = [];
    var _vendor_extraInitializers = [];
    var _reviews_decorators;
    var _reviews_initializers = [];
    var _reviews_extraInitializers = [];
    var _leads_decorators;
    var _leads_initializers = [];
    var _leads_extraInitializers = [];
    var _savedListings_decorators;
    var _savedListings_initializers = [];
    var _savedListings_extraInitializers = [];
    var _notifications_decorators;
    var _notifications_initializers = [];
    var _notifications_extraInitializers = [];
    var _comments_decorators;
    var _comments_initializers = [];
    var _comments_extraInitializers = [];
    var _follows_decorators;
    var _follows_initializers = [];
    var _follows_extraInitializers = [];
    var _affiliate_decorators;
    var _affiliate_initializers = [];
    var _affiliate_extraInitializers = [];
    var User = _classThis = /** @class */ (function () {
        function User_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.password = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _password_initializers, void 0));
            this.email = (__runInitializers(this, _password_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.phone = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
            this.fullName = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _fullName_initializers, void 0));
            this.avatarUrl = (__runInitializers(this, _fullName_extraInitializers), __runInitializers(this, _avatarUrl_initializers, void 0));
            this.role = (__runInitializers(this, _avatarUrl_extraInitializers), __runInitializers(this, _role_initializers, void 0));
            this.isActive = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.isEmailVerified = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _isEmailVerified_initializers, void 0));
            this.isPhoneVerified = (__runInitializers(this, _isEmailVerified_extraInitializers), __runInitializers(this, _isPhoneVerified_initializers, void 0));
            this.isOnline = (__runInitializers(this, _isPhoneVerified_extraInitializers), __runInitializers(this, _isOnline_initializers, void 0));
            this.city = (__runInitializers(this, _isOnline_extraInitializers), __runInitializers(this, _city_initializers, void 0));
            this.state = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _state_initializers, void 0));
            this.country = (__runInitializers(this, _state_extraInitializers), __runInitializers(this, _country_initializers, void 0));
            this.googleId = (__runInitializers(this, _country_extraInitializers), __runInitializers(this, _googleId_initializers, void 0));
            this.provider = (__runInitializers(this, _googleId_extraInitializers), __runInitializers(this, _provider_initializers, void 0));
            this.deviceToken = (__runInitializers(this, _provider_extraInitializers), __runInitializers(this, _deviceToken_initializers, void 0));
            this.pushSubscriptions = (__runInitializers(this, _deviceToken_extraInitializers), __runInitializers(this, _pushSubscriptions_initializers, void 0));
            this.lastLoginAt = (__runInitializers(this, _pushSubscriptions_extraInitializers), __runInitializers(this, _lastLoginAt_initializers, void 0));
            this.lastLogoutAt = (__runInitializers(this, _lastLoginAt_extraInitializers), __runInitializers(this, _lastLogoutAt_initializers, void 0));
            this.lastActiveAt = (__runInitializers(this, _lastLogoutAt_extraInitializers), __runInitializers(this, _lastActiveAt_initializers, void 0));
            this.createdAt = (__runInitializers(this, _lastActiveAt_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            // Relations
            this.vendor = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _vendor_initializers, void 0));
            this.reviews = (__runInitializers(this, _vendor_extraInitializers), __runInitializers(this, _reviews_initializers, void 0));
            this.leads = (__runInitializers(this, _reviews_extraInitializers), __runInitializers(this, _leads_initializers, void 0));
            this.savedListings = (__runInitializers(this, _leads_extraInitializers), __runInitializers(this, _savedListings_initializers, void 0));
            this.notifications = (__runInitializers(this, _savedListings_extraInitializers), __runInitializers(this, _notifications_initializers, void 0));
            this.comments = (__runInitializers(this, _notifications_extraInitializers), __runInitializers(this, _comments_initializers, void 0));
            this.follows = (__runInitializers(this, _comments_extraInitializers), __runInitializers(this, _follows_initializers, void 0));
            this.affiliate = (__runInitializers(this, _follows_extraInitializers), __runInitializers(this, _affiliate_initializers, void 0));
            __runInitializers(this, _affiliate_extraInitializers);
        }
        return User_1;
    }());
    __setFunctionName(_classThis, "User");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _password_decorators = [(0, typeorm_1.Column)({ nullable: true, select: false })];
        _email_decorators = [(0, typeorm_1.Column)({ unique: true })];
        _phone_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 20 })];
        _fullName_decorators = [(0, typeorm_1.Column)({ name: 'full_name' })];
        _avatarUrl_decorators = [(0, typeorm_1.Column)({ name: 'avatar_url', nullable: true, type: 'text' })];
        _role_decorators = [(0, typeorm_1.Column)({
                type: 'enum',
                enum: UserRole,
                default: UserRole.USER,
            })];
        _isActive_decorators = [(0, typeorm_1.Column)({ name: 'is_active', default: true })];
        _isEmailVerified_decorators = [(0, typeorm_1.Column)({ name: 'is_email_verified', default: false })];
        _isPhoneVerified_decorators = [(0, typeorm_1.Column)({ name: 'is_phone_verified', default: false })];
        _isOnline_decorators = [(0, typeorm_1.Column)({ name: 'is_online', default: false }), (0, typeorm_1.Index)()];
        _city_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 100 })];
        _state_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 100 })];
        _country_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 100, default: 'Pakistan' })];
        _googleId_decorators = [(0, typeorm_1.Column)({ name: 'google_id', nullable: true, unique: true })];
        _provider_decorators = [(0, typeorm_1.Column)({ name: 'provider', nullable: true, default: 'local' })];
        _deviceToken_decorators = [(0, typeorm_1.Column)({ name: 'device_token', nullable: true, type: 'text' })];
        _pushSubscriptions_decorators = [(0, typeorm_1.Column)({ name: 'push_subscriptions', nullable: true, type: 'jsonb', default: '[]' })];
        _lastLoginAt_decorators = [(0, typeorm_1.Column)({ name: 'last_login_at', nullable: true, type: 'timestamp' })];
        _lastLogoutAt_decorators = [(0, typeorm_1.Column)({ name: 'last_logout_at', nullable: true, type: 'timestamp' })];
        _lastActiveAt_decorators = [(0, typeorm_1.Column)({ name: 'last_active_at', nullable: true, type: 'timestamp' })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ name: 'created_at' })];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ name: 'updated_at' })];
        _vendor_decorators = [(0, typeorm_1.OneToOne)(function () { return vendor_entity_1.Vendor; }, function (vendor) { return vendor.user; })];
        _reviews_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return review_entity_1.Review; }, function (review) { return review.user; })];
        _leads_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return lead_entity_1.Lead; }, function (lead) { return lead.user; })];
        _savedListings_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return favorite_entity_1.SavedListing; }, function (savedListing) { return savedListing.user; })];
        _notifications_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return notification_entity_1.Notification; }, function (notification) { return notification.user; })];
        _comments_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return comment_entity_1.Comment; }, function (comment) { return comment.user; })];
        _follows_decorators = [(0, class_transformer_1.Exclude)(), (0, typeorm_1.OneToMany)(function () { return follow_entity_1.Follow; }, function (follow) { return follow.user; })];
        _affiliate_decorators = [(0, typeorm_1.OneToOne)(function () { return affiliate_entity_1.Affiliate; }, function (affiliate) { return affiliate.user; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _password_decorators, { kind: "field", name: "password", static: false, private: false, access: { has: function (obj) { return "password" in obj; }, get: function (obj) { return obj.password; }, set: function (obj, value) { obj.password = value; } }, metadata: _metadata }, _password_initializers, _password_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: function (obj) { return "email" in obj; }, get: function (obj) { return obj.email; }, set: function (obj, value) { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: function (obj) { return "phone" in obj; }, get: function (obj) { return obj.phone; }, set: function (obj, value) { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
        __esDecorate(null, null, _fullName_decorators, { kind: "field", name: "fullName", static: false, private: false, access: { has: function (obj) { return "fullName" in obj; }, get: function (obj) { return obj.fullName; }, set: function (obj, value) { obj.fullName = value; } }, metadata: _metadata }, _fullName_initializers, _fullName_extraInitializers);
        __esDecorate(null, null, _avatarUrl_decorators, { kind: "field", name: "avatarUrl", static: false, private: false, access: { has: function (obj) { return "avatarUrl" in obj; }, get: function (obj) { return obj.avatarUrl; }, set: function (obj, value) { obj.avatarUrl = value; } }, metadata: _metadata }, _avatarUrl_initializers, _avatarUrl_extraInitializers);
        __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: function (obj) { return "role" in obj; }, get: function (obj) { return obj.role; }, set: function (obj, value) { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: function (obj) { return "isActive" in obj; }, get: function (obj) { return obj.isActive; }, set: function (obj, value) { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _isEmailVerified_decorators, { kind: "field", name: "isEmailVerified", static: false, private: false, access: { has: function (obj) { return "isEmailVerified" in obj; }, get: function (obj) { return obj.isEmailVerified; }, set: function (obj, value) { obj.isEmailVerified = value; } }, metadata: _metadata }, _isEmailVerified_initializers, _isEmailVerified_extraInitializers);
        __esDecorate(null, null, _isPhoneVerified_decorators, { kind: "field", name: "isPhoneVerified", static: false, private: false, access: { has: function (obj) { return "isPhoneVerified" in obj; }, get: function (obj) { return obj.isPhoneVerified; }, set: function (obj, value) { obj.isPhoneVerified = value; } }, metadata: _metadata }, _isPhoneVerified_initializers, _isPhoneVerified_extraInitializers);
        __esDecorate(null, null, _isOnline_decorators, { kind: "field", name: "isOnline", static: false, private: false, access: { has: function (obj) { return "isOnline" in obj; }, get: function (obj) { return obj.isOnline; }, set: function (obj, value) { obj.isOnline = value; } }, metadata: _metadata }, _isOnline_initializers, _isOnline_extraInitializers);
        __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: function (obj) { return "city" in obj; }, get: function (obj) { return obj.city; }, set: function (obj, value) { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
        __esDecorate(null, null, _state_decorators, { kind: "field", name: "state", static: false, private: false, access: { has: function (obj) { return "state" in obj; }, get: function (obj) { return obj.state; }, set: function (obj, value) { obj.state = value; } }, metadata: _metadata }, _state_initializers, _state_extraInitializers);
        __esDecorate(null, null, _country_decorators, { kind: "field", name: "country", static: false, private: false, access: { has: function (obj) { return "country" in obj; }, get: function (obj) { return obj.country; }, set: function (obj, value) { obj.country = value; } }, metadata: _metadata }, _country_initializers, _country_extraInitializers);
        __esDecorate(null, null, _googleId_decorators, { kind: "field", name: "googleId", static: false, private: false, access: { has: function (obj) { return "googleId" in obj; }, get: function (obj) { return obj.googleId; }, set: function (obj, value) { obj.googleId = value; } }, metadata: _metadata }, _googleId_initializers, _googleId_extraInitializers);
        __esDecorate(null, null, _provider_decorators, { kind: "field", name: "provider", static: false, private: false, access: { has: function (obj) { return "provider" in obj; }, get: function (obj) { return obj.provider; }, set: function (obj, value) { obj.provider = value; } }, metadata: _metadata }, _provider_initializers, _provider_extraInitializers);
        __esDecorate(null, null, _deviceToken_decorators, { kind: "field", name: "deviceToken", static: false, private: false, access: { has: function (obj) { return "deviceToken" in obj; }, get: function (obj) { return obj.deviceToken; }, set: function (obj, value) { obj.deviceToken = value; } }, metadata: _metadata }, _deviceToken_initializers, _deviceToken_extraInitializers);
        __esDecorate(null, null, _pushSubscriptions_decorators, { kind: "field", name: "pushSubscriptions", static: false, private: false, access: { has: function (obj) { return "pushSubscriptions" in obj; }, get: function (obj) { return obj.pushSubscriptions; }, set: function (obj, value) { obj.pushSubscriptions = value; } }, metadata: _metadata }, _pushSubscriptions_initializers, _pushSubscriptions_extraInitializers);
        __esDecorate(null, null, _lastLoginAt_decorators, { kind: "field", name: "lastLoginAt", static: false, private: false, access: { has: function (obj) { return "lastLoginAt" in obj; }, get: function (obj) { return obj.lastLoginAt; }, set: function (obj, value) { obj.lastLoginAt = value; } }, metadata: _metadata }, _lastLoginAt_initializers, _lastLoginAt_extraInitializers);
        __esDecorate(null, null, _lastLogoutAt_decorators, { kind: "field", name: "lastLogoutAt", static: false, private: false, access: { has: function (obj) { return "lastLogoutAt" in obj; }, get: function (obj) { return obj.lastLogoutAt; }, set: function (obj, value) { obj.lastLogoutAt = value; } }, metadata: _metadata }, _lastLogoutAt_initializers, _lastLogoutAt_extraInitializers);
        __esDecorate(null, null, _lastActiveAt_decorators, { kind: "field", name: "lastActiveAt", static: false, private: false, access: { has: function (obj) { return "lastActiveAt" in obj; }, get: function (obj) { return obj.lastActiveAt; }, set: function (obj, value) { obj.lastActiveAt = value; } }, metadata: _metadata }, _lastActiveAt_initializers, _lastActiveAt_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _vendor_decorators, { kind: "field", name: "vendor", static: false, private: false, access: { has: function (obj) { return "vendor" in obj; }, get: function (obj) { return obj.vendor; }, set: function (obj, value) { obj.vendor = value; } }, metadata: _metadata }, _vendor_initializers, _vendor_extraInitializers);
        __esDecorate(null, null, _reviews_decorators, { kind: "field", name: "reviews", static: false, private: false, access: { has: function (obj) { return "reviews" in obj; }, get: function (obj) { return obj.reviews; }, set: function (obj, value) { obj.reviews = value; } }, metadata: _metadata }, _reviews_initializers, _reviews_extraInitializers);
        __esDecorate(null, null, _leads_decorators, { kind: "field", name: "leads", static: false, private: false, access: { has: function (obj) { return "leads" in obj; }, get: function (obj) { return obj.leads; }, set: function (obj, value) { obj.leads = value; } }, metadata: _metadata }, _leads_initializers, _leads_extraInitializers);
        __esDecorate(null, null, _savedListings_decorators, { kind: "field", name: "savedListings", static: false, private: false, access: { has: function (obj) { return "savedListings" in obj; }, get: function (obj) { return obj.savedListings; }, set: function (obj, value) { obj.savedListings = value; } }, metadata: _metadata }, _savedListings_initializers, _savedListings_extraInitializers);
        __esDecorate(null, null, _notifications_decorators, { kind: "field", name: "notifications", static: false, private: false, access: { has: function (obj) { return "notifications" in obj; }, get: function (obj) { return obj.notifications; }, set: function (obj, value) { obj.notifications = value; } }, metadata: _metadata }, _notifications_initializers, _notifications_extraInitializers);
        __esDecorate(null, null, _comments_decorators, { kind: "field", name: "comments", static: false, private: false, access: { has: function (obj) { return "comments" in obj; }, get: function (obj) { return obj.comments; }, set: function (obj, value) { obj.comments = value; } }, metadata: _metadata }, _comments_initializers, _comments_extraInitializers);
        __esDecorate(null, null, _follows_decorators, { kind: "field", name: "follows", static: false, private: false, access: { has: function (obj) { return "follows" in obj; }, get: function (obj) { return obj.follows; }, set: function (obj, value) { obj.follows = value; } }, metadata: _metadata }, _follows_initializers, _follows_extraInitializers);
        __esDecorate(null, null, _affiliate_decorators, { kind: "field", name: "affiliate", static: false, private: false, access: { has: function (obj) { return "affiliate" in obj; }, get: function (obj) { return obj.affiliate; }, set: function (obj, value) { obj.affiliate = value; } }, metadata: _metadata }, _affiliate_initializers, _affiliate_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        User = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return User = _classThis;
}();
exports.User = User;
