"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Vendor = void 0;
var typeorm_1 = require("typeorm");
var user_entity_1 = require("./user.entity");
var business_entity_1 = require("./business.entity");
var subscription_entity_1 = require("./subscription.entity");
var transaction_entity_1 = require("./transaction.entity");
var comment_reply_entity_1 = require("./comment-reply.entity");
var Vendor = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('vendors')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _userId_decorators;
    var _userId_initializers = [];
    var _userId_extraInitializers = [];
    var _businessName_decorators;
    var _businessName_initializers = [];
    var _businessName_extraInitializers = [];
    var _bio_decorators;
    var _bio_initializers = [];
    var _bio_extraInitializers = [];
    var _businessEmail_decorators;
    var _businessEmail_initializers = [];
    var _businessEmail_extraInitializers = [];
    var _businessPhone_decorators;
    var _businessPhone_initializers = [];
    var _businessPhone_extraInitializers = [];
    var _businessAddress_decorators;
    var _businessAddress_initializers = [];
    var _businessAddress_extraInitializers = [];
    var _gstNumber_decorators;
    var _gstNumber_initializers = [];
    var _gstNumber_extraInitializers = [];
    var _ntnNumber_decorators;
    var _ntnNumber_initializers = [];
    var _ntnNumber_extraInitializers = [];
    var _isVerified_decorators;
    var _isVerified_initializers = [];
    var _isVerified_extraInitializers = [];
    var _verificationDocuments_decorators;
    var _verificationDocuments_initializers = [];
    var _verificationDocuments_extraInitializers = [];
    var _businessHours_decorators;
    var _businessHours_initializers = [];
    var _businessHours_extraInitializers = [];
    var _socialLinks_decorators;
    var _socialLinks_initializers = [];
    var _socialLinks_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _user_decorators;
    var _user_initializers = [];
    var _user_extraInitializers = [];
    var _businesses_decorators;
    var _businesses_initializers = [];
    var _businesses_extraInitializers = [];
    var _subscriptions_decorators;
    var _subscriptions_initializers = [];
    var _subscriptions_extraInitializers = [];
    var _transactions_decorators;
    var _transactions_initializers = [];
    var _transactions_extraInitializers = [];
    var _replies_decorators;
    var _replies_initializers = [];
    var _replies_extraInitializers = [];
    var Vendor = _classThis = /** @class */ (function () {
        function Vendor_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.userId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _userId_initializers, void 0));
            this.businessName = (__runInitializers(this, _userId_extraInitializers), __runInitializers(this, _businessName_initializers, void 0));
            this.bio = (__runInitializers(this, _businessName_extraInitializers), __runInitializers(this, _bio_initializers, void 0));
            this.businessEmail = (__runInitializers(this, _bio_extraInitializers), __runInitializers(this, _businessEmail_initializers, void 0));
            this.businessPhone = (__runInitializers(this, _businessEmail_extraInitializers), __runInitializers(this, _businessPhone_initializers, void 0));
            this.businessAddress = (__runInitializers(this, _businessPhone_extraInitializers), __runInitializers(this, _businessAddress_initializers, void 0));
            this.gstNumber = (__runInitializers(this, _businessAddress_extraInitializers), __runInitializers(this, _gstNumber_initializers, void 0));
            this.ntnNumber = (__runInitializers(this, _gstNumber_extraInitializers), __runInitializers(this, _ntnNumber_initializers, void 0));
            this.isVerified = (__runInitializers(this, _ntnNumber_extraInitializers), __runInitializers(this, _isVerified_initializers, void 0));
            this.verificationDocuments = (__runInitializers(this, _isVerified_extraInitializers), __runInitializers(this, _verificationDocuments_initializers, void 0));
            this.businessHours = (__runInitializers(this, _verificationDocuments_extraInitializers), __runInitializers(this, _businessHours_initializers, void 0));
            this.socialLinks = (__runInitializers(this, _businessHours_extraInitializers), __runInitializers(this, _socialLinks_initializers, void 0));
            this.createdAt = (__runInitializers(this, _socialLinks_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            // Relations
            this.user = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _user_initializers, void 0));
            this.businesses = (__runInitializers(this, _user_extraInitializers), __runInitializers(this, _businesses_initializers, void 0));
            this.subscriptions = (__runInitializers(this, _businesses_extraInitializers), __runInitializers(this, _subscriptions_initializers, void 0));
            this.transactions = (__runInitializers(this, _subscriptions_extraInitializers), __runInitializers(this, _transactions_initializers, void 0));
            this.replies = (__runInitializers(this, _transactions_extraInitializers), __runInitializers(this, _replies_initializers, void 0));
            __runInitializers(this, _replies_extraInitializers);
        }
        return Vendor_1;
    }());
    __setFunctionName(_classThis, "Vendor");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _userId_decorators = [(0, typeorm_1.Column)({ name: 'user_id', type: 'uuid' })];
        _businessName_decorators = [(0, typeorm_1.Column)({ name: 'business_name', nullable: true })];
        _bio_decorators = [(0, typeorm_1.Column)({ nullable: true, type: 'text' })];
        _businessEmail_decorators = [(0, typeorm_1.Column)({ name: 'business_email', nullable: true })];
        _businessPhone_decorators = [(0, typeorm_1.Column)({ name: 'business_phone', length: 20, nullable: true })];
        _businessAddress_decorators = [(0, typeorm_1.Column)({ name: 'business_address', nullable: true, type: 'text' })];
        _gstNumber_decorators = [(0, typeorm_1.Column)({ name: 'gst_number', nullable: true, length: 15 })];
        _ntnNumber_decorators = [(0, typeorm_1.Column)({ name: 'ntn_number', nullable: true, length: 15 })];
        _isVerified_decorators = [(0, typeorm_1.Column)({ name: 'is_verified', default: false })];
        _verificationDocuments_decorators = [(0, typeorm_1.Column)({ name: 'verification_documents', nullable: true, type: 'jsonb' })];
        _businessHours_decorators = [(0, typeorm_1.Column)({ name: 'business_hours', nullable: true, type: 'jsonb' })];
        _socialLinks_decorators = [(0, typeorm_1.Column)({ name: 'social_links', nullable: true, type: 'jsonb', default: '[]' })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ name: 'created_at' })];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ name: 'updated_at' })];
        _user_decorators = [(0, typeorm_1.OneToOne)(function () { return user_entity_1.User; }, function (user) { return user.vendor; }), (0, typeorm_1.JoinColumn)({ name: 'user_id' })];
        _businesses_decorators = [(0, typeorm_1.OneToMany)(function () { return business_entity_1.Listing; }, function (listing) { return listing.vendor; })];
        _subscriptions_decorators = [(0, typeorm_1.OneToMany)(function () { return subscription_entity_1.Subscription; }, function (subscription) { return subscription.vendor; })];
        _transactions_decorators = [(0, typeorm_1.OneToMany)(function () { return transaction_entity_1.Transaction; }, function (transaction) { return transaction.vendor; })];
        _replies_decorators = [(0, typeorm_1.OneToMany)(function () { return comment_reply_entity_1.CommentReply; }, function (reply) { return reply.vendor; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _userId_decorators, { kind: "field", name: "userId", static: false, private: false, access: { has: function (obj) { return "userId" in obj; }, get: function (obj) { return obj.userId; }, set: function (obj, value) { obj.userId = value; } }, metadata: _metadata }, _userId_initializers, _userId_extraInitializers);
        __esDecorate(null, null, _businessName_decorators, { kind: "field", name: "businessName", static: false, private: false, access: { has: function (obj) { return "businessName" in obj; }, get: function (obj) { return obj.businessName; }, set: function (obj, value) { obj.businessName = value; } }, metadata: _metadata }, _businessName_initializers, _businessName_extraInitializers);
        __esDecorate(null, null, _bio_decorators, { kind: "field", name: "bio", static: false, private: false, access: { has: function (obj) { return "bio" in obj; }, get: function (obj) { return obj.bio; }, set: function (obj, value) { obj.bio = value; } }, metadata: _metadata }, _bio_initializers, _bio_extraInitializers);
        __esDecorate(null, null, _businessEmail_decorators, { kind: "field", name: "businessEmail", static: false, private: false, access: { has: function (obj) { return "businessEmail" in obj; }, get: function (obj) { return obj.businessEmail; }, set: function (obj, value) { obj.businessEmail = value; } }, metadata: _metadata }, _businessEmail_initializers, _businessEmail_extraInitializers);
        __esDecorate(null, null, _businessPhone_decorators, { kind: "field", name: "businessPhone", static: false, private: false, access: { has: function (obj) { return "businessPhone" in obj; }, get: function (obj) { return obj.businessPhone; }, set: function (obj, value) { obj.businessPhone = value; } }, metadata: _metadata }, _businessPhone_initializers, _businessPhone_extraInitializers);
        __esDecorate(null, null, _businessAddress_decorators, { kind: "field", name: "businessAddress", static: false, private: false, access: { has: function (obj) { return "businessAddress" in obj; }, get: function (obj) { return obj.businessAddress; }, set: function (obj, value) { obj.businessAddress = value; } }, metadata: _metadata }, _businessAddress_initializers, _businessAddress_extraInitializers);
        __esDecorate(null, null, _gstNumber_decorators, { kind: "field", name: "gstNumber", static: false, private: false, access: { has: function (obj) { return "gstNumber" in obj; }, get: function (obj) { return obj.gstNumber; }, set: function (obj, value) { obj.gstNumber = value; } }, metadata: _metadata }, _gstNumber_initializers, _gstNumber_extraInitializers);
        __esDecorate(null, null, _ntnNumber_decorators, { kind: "field", name: "ntnNumber", static: false, private: false, access: { has: function (obj) { return "ntnNumber" in obj; }, get: function (obj) { return obj.ntnNumber; }, set: function (obj, value) { obj.ntnNumber = value; } }, metadata: _metadata }, _ntnNumber_initializers, _ntnNumber_extraInitializers);
        __esDecorate(null, null, _isVerified_decorators, { kind: "field", name: "isVerified", static: false, private: false, access: { has: function (obj) { return "isVerified" in obj; }, get: function (obj) { return obj.isVerified; }, set: function (obj, value) { obj.isVerified = value; } }, metadata: _metadata }, _isVerified_initializers, _isVerified_extraInitializers);
        __esDecorate(null, null, _verificationDocuments_decorators, { kind: "field", name: "verificationDocuments", static: false, private: false, access: { has: function (obj) { return "verificationDocuments" in obj; }, get: function (obj) { return obj.verificationDocuments; }, set: function (obj, value) { obj.verificationDocuments = value; } }, metadata: _metadata }, _verificationDocuments_initializers, _verificationDocuments_extraInitializers);
        __esDecorate(null, null, _businessHours_decorators, { kind: "field", name: "businessHours", static: false, private: false, access: { has: function (obj) { return "businessHours" in obj; }, get: function (obj) { return obj.businessHours; }, set: function (obj, value) { obj.businessHours = value; } }, metadata: _metadata }, _businessHours_initializers, _businessHours_extraInitializers);
        __esDecorate(null, null, _socialLinks_decorators, { kind: "field", name: "socialLinks", static: false, private: false, access: { has: function (obj) { return "socialLinks" in obj; }, get: function (obj) { return obj.socialLinks; }, set: function (obj, value) { obj.socialLinks = value; } }, metadata: _metadata }, _socialLinks_initializers, _socialLinks_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _user_decorators, { kind: "field", name: "user", static: false, private: false, access: { has: function (obj) { return "user" in obj; }, get: function (obj) { return obj.user; }, set: function (obj, value) { obj.user = value; } }, metadata: _metadata }, _user_initializers, _user_extraInitializers);
        __esDecorate(null, null, _businesses_decorators, { kind: "field", name: "businesses", static: false, private: false, access: { has: function (obj) { return "businesses" in obj; }, get: function (obj) { return obj.businesses; }, set: function (obj, value) { obj.businesses = value; } }, metadata: _metadata }, _businesses_initializers, _businesses_extraInitializers);
        __esDecorate(null, null, _subscriptions_decorators, { kind: "field", name: "subscriptions", static: false, private: false, access: { has: function (obj) { return "subscriptions" in obj; }, get: function (obj) { return obj.subscriptions; }, set: function (obj, value) { obj.subscriptions = value; } }, metadata: _metadata }, _subscriptions_initializers, _subscriptions_extraInitializers);
        __esDecorate(null, null, _transactions_decorators, { kind: "field", name: "transactions", static: false, private: false, access: { has: function (obj) { return "transactions" in obj; }, get: function (obj) { return obj.transactions; }, set: function (obj, value) { obj.transactions = value; } }, metadata: _metadata }, _transactions_initializers, _transactions_extraInitializers);
        __esDecorate(null, null, _replies_decorators, { kind: "field", name: "replies", static: false, private: false, access: { has: function (obj) { return "replies" in obj; }, get: function (obj) { return obj.replies; }, set: function (obj, value) { obj.replies = value; } }, metadata: _metadata }, _replies_initializers, _replies_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Vendor = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Vendor = _classThis;
}();
exports.Vendor = Vendor;
